services:
  - type: web
    name: interview-intelligence-system
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: interview-intelligence-db
          property: connectionString
